---
title: "Basic Seurat Analysis"
author: "Deniz Goekbuget"
date: "2024-01-26"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 3. Basic Seurat Analysis
```{r}
#Load packages and data
library(Seurat)
library(SeuratDisk)
library(dplyr)
library(patchwork)
library(harmony)
library(ggplot2)
library(deMULTIplex2)

#Read in preprocessed seurat objects
infiles <- list.files(path = "/blellochlab/data1/deniz/analysis/hx-analyses", pattern = "-nodups-seurat.rds", recursive = TRUE, full.names = TRUE)
```

### 3.1 HXRB01 (DC differentiation using kit)
```{r}
dat <- readRDS(infiles[2])
dat[["batch"]] <- "DC1"
dat2 <- readRDS(infiles[3])
dat2[["batch"]] <- "DC2"

#Integrate data
dat <- merge(dat,y=dat2)

#QC
VlnPlot(dat, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3,group.by = "condition",pt.size=F)
```
```{r}
plot1 <- FeatureScatter(dat, feature1 = "nFeature_RNA", feature2 = "percent.mt") + ggtitle("No. Features")
plot2 <- FeatureScatter(dat, feature1 = "nCount_RNA", feature2 = "nFeature_RNA") + ggtitle("No. RNA Molecules")
plot1 + plot2
```
```{r}
high_mito <- quantile(dat[["percent.mt"]]$percent.mt, probs=0.98) #Overwrite with 20
high_mito <- 20
low_ft <- quantile(dat[["nFeature_RNA"]]$nFeature_RNA, probs=0.02)
high_ft <- quantile(dat[["nFeature_RNA"]]$nFeature_RNA, probs=0.98)
barplot(c(high_mito,low_ft,high_ft),main="Cutoffs",names=c("High Mt DNA","Low Features","High Features"),log="y", ylim=c(1,5000))
```
```{r}
## Remove unwanted cells
dat <- subset(dat, subset = percent.mt < high_mito & nFeature_RNA > low_ft & nFeature_RNA < high_ft)
## Process
dat <- NormalizeData(dat,verbose=F) %>% FindVariableFeatures(verbose=F) %>% ScaleData(verbose=F) %>% RunPCA(verbose=F)
dat <- RunUMAP(dat,dims=1:20,reduction='pca',reduction.name = "umap.unintegrated")
DimPlot(dat,reduction = "umap.unintegrated",cols="Spectral", shuffle=T,group.by=c("batch","sample"))
```
```{r}
#saveRDS(dat,file.path("/blellochlab/data1/deniz/analysis/hx-analyses/hxrb01/hxrb01-nodups-unintegrated.rds"))
readRDS(file.path("/blellochlab/data1/deniz/analysis/hx-analyses/hxrb01/hxrb01-nodups-unintegrated.rds"))
dat <- IntegrateLayers(object = dat, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca",
    verbose = FALSE)
dat[["RNA"]] <- JoinLayers(dat[["RNA"]])
dat <- FindNeighbors(dat, reduction = "integrated.cca", dims = 1:20)
dat <- FindClusters(dat, resolution = 1)
dat <- RunUMAP(dat, dims = 1:20, reduction = "integrated.cca")
# Visualization
DimPlot(dat, reduction = "umap", shuffle=T, label=T, repel=T, group.by = c("batch", "seurat_clusters"))
```
```{r}
saveRDS(dat,file.path("/blellochlab/data1/deniz/analysis/hx-analyses/hxrb01/hxrb01-nodups-integrated.rds"))
```

### 3.2 HXDGRB02 (Japanese DC differentiation samples)
```{r}
dat <- readRDS(infiles[1])

#QC
VlnPlot(dat, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3,group.by = "condition",pt.size=F)
```
```{r}
plot1 <- FeatureScatter(dat, feature1 = "nFeature_RNA", feature2 = "percent.mt") + ggtitle("No. Features")
plot2 <- FeatureScatter(dat, feature1 = "nCount_RNA", feature2 = "nFeature_RNA") + ggtitle("No. RNA Molecules")
plot1 + plot2
```
```{r}
high_mito <- quantile(dat[["percent.mt"]]$percent.mt, probs=0.98) #Overwrite with 20
high_mito <- 20
low_ft <- quantile(dat[["nFeature_RNA"]]$nFeature_RNA, probs=0.02)
high_ft <- quantile(dat[["nFeature_RNA"]]$nFeature_RNA, probs=0.98)
barplot(c(high_mito,low_ft,high_ft),main="Cutoffs",names=c("High Mt DNA","Low Features","High Features"),log="y", ylim=c(1,5000))
```
```{r, fig.width=12}
## Remove unwanted cells
dat <- subset(dat, subset = percent.mt < high_mito & nFeature_RNA > low_ft & nFeature_RNA < high_ft) # ~2000 cells remaining
## Process
dat <- NormalizeData(dat,verbose=F) %>% FindVariableFeatures(verbose=F) %>% ScaleData(verbose=F) %>% RunPCA(verbose=F)
dat <- RunUMAP(dat,dims=1:20,reduction='pca')
dat <- FindNeighbors(dat, reduction = "pca", dims = 1:20)
dat <- FindClusters(dat)
DimPlot(dat,reduction = "umap", shuffle=T,group.by=c("condition","seurat_clusters"))
```
```{r}
saveRDS(dat,file.path("/blellochlab/data1/deniz/analysis/hx-analyses/hxdgrb02/hxrb02-nodups-processed.rds"))
```

### 3.3 HXRB03 (HX DC differentiation Experiment #1)
```{r}
dat <- readRDS(infiles[4])

#QC
VlnPlot(dat, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3,group.by = "condition",pt.size=F)
```
```{r}
plot1 <- FeatureScatter(dat, feature1 = "nFeature_RNA", feature2 = "percent.mt") + ggtitle("No. Features")
plot2 <- FeatureScatter(dat, feature1 = "nCount_RNA", feature2 = "nFeature_RNA") + ggtitle("No. RNA Molecules")
plot1 + plot2
```
```{r}
high_mito <- quantile(dat[["percent.mt"]]$percent.mt, probs=0.98) #Overwrite with 20
high_mito <- 20
low_ft <- quantile(dat[["nFeature_RNA"]]$nFeature_RNA, probs=0.02)
high_ft <- quantile(dat[["nFeature_RNA"]]$nFeature_RNA, probs=0.98)
barplot(c(high_mito,low_ft,high_ft),main="Cutoffs",names=c("High Mt DNA","Low Features","High Features"),log="y", ylim=c(1,5000))
```
```{r, fig.width=12,fig.height=7}
## Remove unwanted cells
dat <- subset(dat, subset = percent.mt < high_mito & nFeature_RNA > low_ft & nFeature_RNA < high_ft) # ~4500 cells remaining
## Process
dat <- NormalizeData(dat,verbose=F) %>% FindVariableFeatures(verbose=F) %>% ScaleData(verbose=F) %>% RunPCA(verbose=F)
dat <- RunUMAP(dat,dims=1:20,reduction='pca')
dat <- FindNeighbors(dat, reduction = "pca", dims = 1:20)
dat <- FindClusters(dat)
DimPlot(dat,reduction = "umap", shuffle=T,group.by=c("condition","seurat_clusters"))
```
```{r}
saveRDS(dat,file.path("/blellochlab/data1/deniz/analysis/hx-analyses/hxrb03/hxrb03-nodups-processed.rds"))
```

### 3.3 HXRB04 (HX DC differentiation Experiment #2)
```{r}
dat <- readRDS(infiles[5])

#QC
VlnPlot(dat, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3,group.by = "condition",pt.size=F)
```
```{r}
plot1 <- FeatureScatter(dat, feature1 = "nFeature_RNA", feature2 = "percent.mt") + ggtitle("No. Features")
plot2 <- FeatureScatter(dat, feature1 = "nCount_RNA", feature2 = "nFeature_RNA") + ggtitle("No. RNA Molecules")
plot1 + plot2
```
```{r}
high_mito <- quantile(dat[["percent.mt"]]$percent.mt, probs=0.98) #Overwrite with 20
high_mito <- 20
low_ft <- quantile(dat[["nFeature_RNA"]]$nFeature_RNA, probs=0.02)
high_ft <- quantile(dat[["nFeature_RNA"]]$nFeature_RNA, probs=0.98)
barplot(c(high_mito,low_ft,high_ft),main="Cutoffs",names=c("High Mt DNA","Low Features","High Features"),log="y", ylim=c(1,5000))
```
```{r, fig.width=12,fig.height=7}
## Remove unwanted cells
dat <- subset(dat, subset = percent.mt < high_mito & nFeature_RNA > low_ft & nFeature_RNA < high_ft) # ~9338 cells remaining
## Process
dat <- NormalizeData(dat,verbose=F) %>% FindVariableFeatures(verbose=F) %>% ScaleData(verbose=F) %>% RunPCA(verbose=F)
dat <- RunUMAP(dat,dims=1:20,reduction='pca')
dat <- FindNeighbors(dat, reduction = "pca", dims = 1:20)
dat <- FindClusters(dat)
DimPlot(dat,reduction = "umap", shuffle=T,group.by=c("condition","seurat_clusters"))
```
```{r}
saveRDS(dat,file.path("/blellochlab/data1/deniz/analysis/hx-analyses/hxrb04/hxrb04-nodups-processed.rds"))
```

